Repository Devfolio-team/Devfolio-Client, pull requests merged in 2021-05, with the labels that each got.

#257 Refactor: LoginModalDialog, DivisionLine 스토리북 추가, ModalDialog 수정
  src/components/DivisionLine/DivisionLine.stories.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.stories.js
  src/containers/ModalDialog/ModalDialog.js
  src/containers/ModalDialog/ModalDialog.stories.js
  src/containers/WithdrawalModalDialog/WithdrawalModalDialog.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
Labels: 🔨 Refactor

#262 Refactor: Storybook 수정 및 추가, ProjectPage 좋아요 마크업, 스타일 수정
  src/components/ProjectExplanation/ProjectExplanation.stories.js
  src/containers/LoginModalDialog/LoginModalDialog.stories.js
  src/containers/ModalDialog/ModalDialog.stories.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#266 ChipInputSearch의 html tag datalist를 직접 UI 구현, ChipInputSearch에 datalist의 autocomplete에서 엔터나 클릭을 했을때 자동으로 요소가 추가가 되는 기능 구현, ChipInputSearch에 datalist의 autocomplete 스타일링 작업, ProjectThumbnail, RadioButton storybook접근성 이슈 해결, 선택하려는 기술 스택이 없다면 그 기술스택을 추가 요청을 할 수 있는 기능 구현 및 UI 구현
  src/apis/ajax.js
  src/apis/techStacks.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/Input/Input.js
  src/components/RadioButton/RadioButton.stories.js
  src/containers/NewTechStackModalDialog/NewTechStackModalDialog.js
  src/containers/index.js
Labels: ✨ Feature

#279 선택하려는 기술 스택이 없을때 기술스택을 추가 요청을 한 후 요청이 완료됐다는 메세지를 띄워주는 모달 다이얼로그 구현, 사용하고 있는 이벤트 핸들러 같은 함수들에 useCallback을 사용하여 최적화 작업
  src/components/ChipInputSearch/ChipInputSearch.js
  src/containers/ConfirmModalDialog/ConfirmModalDialog.js
  src/containers/NewTechStackModalDialog/NewTechStackModalDialog.js
  src/containers/index.js
Labels: ✨ Feature

#287 유저가 좋아요를 누른 프로젝트만 모아서 볼 수 있는 페이지 생성 및 기능 구현
  src/apis/ajax.js
  src/apis/project.js
  src/pages/FavoriteProject/FavoriteProjectPage.js
Labels: ✨ Feature

#290 특정 유저가 좋아한 프로젝트만 모아서 보는 페이지의 무한스크롤 구현
  src/apis/project.js
  src/components/FetchMore/FetchMore.js
  src/components/index.js
  src/pages/FavoriteProject/FavoriteProjectPage.js
Labels: ✨ Feature

#293 프로젝트 수정 및 조회 페이지에서 기획의도라는 타이틀을 기획 의도 및 소개라고 바꿔주기
  src/components/PlanIntention/PlanIntention.js
  src/pages/Project/ProjectPage.js
Labels: 🔨 Refactor

#315 프로젝트 수정 페이지에 접근했을때 팀원 목록을 렌더링해주는 로직 구현, 로그인 안된 유저도 검색창 접근할 수 있게끔 수정
  src/components/Input/Input.js
  src/components/ProjectTeamMember/ProjectTeamMember.js
  src/components/UserNavigator/UserNavigator.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/pages/Search/SearchPage.js
Labels: ✨ Feature

#319 팀원 목록 유효성 검사 리팩토링
  src/components/ProjectTeamMember/ProjectTeamMember.js
  src/containers/ProjectEditForm/ProjectEditForm.js
Labels: 🔨 Refactor

#322 Refactor: 좋아요한 프로젝트가 없을시에 무한으로 스켈레톤 UI가 뜨던 이슈 해결
  src/components/EmptyMessage/EmptyMessage.js
  src/components/EmptyMessage/EmptyMessage.stories.js
  src/components/index.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/PortfolioContents/PortfolioContents.js
  src/containers/UseTechStacks/UseTechStacks.js
  src/pages/FavoriteProject/FavoriteProjectPage.js
Labels: 🔨 Refactor
