Repository Devfolio-team/Devfolio-Client, pull requests merged in 2021-04, with the labels that each got.

#14 Prettier 설정으로 인한 코드 스타일 자동 변경
  src/components/Button/Button.js
Labels: 🌈 Style

#16 Components 폴더내 index.js 변경
  src/components/index.js
Labels: ✨ Feature

#17 utils 폴더내 index.js 변경
  src/utils/index.js
Labels: ✨ Feature

#18 Button component내의 hex code color들 color.js의 변수들로 변경
  src/components/Button/Button.js
Labels: ✨ Feature

#19 feat: Heading Component 생성
  src/components/Heading/Heading.js
  src/components/Heading/Heading.stories.js
  src/components/index.js
Labels: ✨ Feature

#22 Bugfix: 오타 때문에 스토리북 description 안되는 것 수정
  src/components/Heading/Heading.js
  src/components/Heading/Heading.stories.js
Labels: 🐞 BugFix

#23 Radio Button Component 생성 및 prettier style 해결
  src/components/Button/Button.stories.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.stories.js
Labels: ✨ Feature

#24 index.js에 RadioButton 컴포넌트 export 추가
  src/components/index.js
Labels: ✨ Feature

#25 Input Component와 스토리북 생성
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
  src/components/index.js
Labels: ✨ Feature

#26 feat: Paragraph 컴포넌트 생성
  src/components/Paragraph/Paragraph.js
  src/components/Paragraph/Paragraph.stories.js
  src/components/index.js
Labels: ✨ Feature

#27 Button Component의 storybook의 description에 안뜨던것 수정
  src/components/Button/Button.js
Labels: 🐞 BugFix

#31 Input Component에 label element 추가
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
Labels: 🔨 Refactor

#32 Selectbox Component와 스토리북 생성
  src/components/Selectbox/Selectbox.js
  src/components/Selectbox/Selectbox.stories.js
  src/components/index.js
Labels: ✨ Feature

#33 TextArea 컴포넌트 생성
  src/components/TextArea/TextArea.js
  src/components/TextArea/TextArea.stories.js
  src/components/index.js
Labels: ✨ Feature

#36 Feat: SVGIcon Component 생성
  src/assets/Angry.svg
  src/assets/Blog.svg
  src/assets/Email.svg
  src/assets/Empty.svg
  src/assets/Github.svg
  src/assets/Google.svg
  src/assets/HeartBlack.svg
  src/assets/HeartEmpty.svg
  src/assets/HeartRed.svg
  src/assets/LogoBlack.svg
  src/assets/LogoWhite.svg
  src/assets/Sad.svg
  src/assets/Smile.svg
  src/components/SVGIcon/SVGIcon.js
  src/components/SVGIcon/SVGIcon.stories.js
  src/components/index.js
Labels: ✨ Feature

#39 Feat: Logo Component 생성
  src/assets/LogoBlack.svg
  src/assets/LogoWhite.svg
  src/components/Logo/Logo.js
  src/components/Logo/Logo.stories.js
  src/components/SVGIcon/SVGIcon.js
  src/components/SVGIcon/SVGIcon.stories.js
  src/components/index.js
Labels: ✨ Feature

#46 DND 컴포넌트 기본적인 기능 구현 및 틀 생성
  src/components/A11yHidden/A11yHidden.js
  src/components/A11yHidden/A11yHidden.stories.js
  src/components/DND/DND.js
  src/components/DND/DND.stories.js
  src/components/Image/Image.js
  src/components/Image/Image.stories.js
  src/components/index.js
Labels: ✨ Feature

#51 Input component 리팩토링
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
Labels: 🔨 Refactor

#52 DND component 리팩토링
  src/components/DND/DND.js
  src/components/DND/DND.stories.js
Labels: 🔨 Refactor

#53 Feat: LoginDialog Component 생성
  src/components/Button/Button.js
  src/components/Dialog/Dialog.js
  src/components/Dialog/Dialog.stories.js
  src/components/Heading/Heading.js
  src/components/Input/Input.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.stories.js
  src/components/index.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/containers/LoginModalDialog/LoginModalDialog.stories.js
  src/containers/index.js
Labels: ✨ Feature

#54 Feat: Portal Component 생성 및 LoginModalDialog 컴포넌트에 적용
  src/components/Portal/Portal.js
  src/components/index.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
Labels: ✨ Feature

#63 ChipInputSearch Component 생성 진행중
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ChipInputSearch/ChipInputSearch.stories.js
  src/components/index.js
Labels: ✨ Feature

#64 LoginModalDialog 컴포넌트 접근성 기능 추가 및 스타일 수정
  src/components/Button/Button.js
  src/components/Dialog/Dialog.js
  src/components/Input/Input.js
  src/components/Modal/Modal.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
Labels: ✨ Feature, 🌈 Style, 🔨 Refactor

#65 Button, Image, Input Component의 styled components 수정 및 스토리북 수정
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Image/Image.js
  src/components/Image/Image.stories.js
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
  src/components/RadioButton/RadioButton.stories.js
  src/components/Selectbox/Selectbox.stories.js
Labels: 🐞 BugFix

#66 Styled-components에 css명과 같은 attribute를 props로 할당했을때 그대로 적용되는 버그 수정
  src/components/Dialog/Dialog.js
  src/components/Heading/Heading.js
  src/components/Paragraph/Paragraph.js
  src/components/SVGIcon/SVGIcon.js
  src/components/TextArea/TextArea.js
  src/containers/LoginModalDialog/LoginModalDialog.js
Labels: 🐞 BugFix

#67 ChipInputSearch Component와 스토리북 생성 완료
  public/style/_custom-reset.css
  src/assets/Camera.svg
  src/assets/Folder.svg
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ChipInputSearch/ChipInputSearch.stories.js
  src/components/Container/Container.js
  src/components/Container/Container.stories.js
  src/components/DND/DND.js
  src/components/Image/Image.js
  src/components/Image/Image.stories.js
  src/components/SVGIcon/SVGIcon.js
  src/styles/_custom-reset.scss
Labels: ✨ Feature

#70 SignupModalDialog Component 생성
  src/components/Dialog/Dialog.js
  src/components/Input/Input.js
  src/components/Logo/Logo.stories.js
  src/components/Modal/Modal.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/containers/SignupModalDialog/SignupModalDialog.js
  src/containers/SignupModalDialog/SignupModalDialog.stories.js
  src/containers/index.js
  src/utils/color.js
Labels: ✨ Feature

#73 Bugfix: DND.stories.js 파일 내부에서 args에 id를 전해주지 않아 storybook에서의 접근성 violation 뜨는 문제
  src/components/DND/DND.stories.js
Labels: 🐞 BugFix

#77 프로젝트 이름 컴포넌트 생성, RadioButton 컴포넌트 리팩토링, Input 컴포넌트 리팩토링, Selectbox 컴포넌트 리팩토링
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
  src/components/ProjectName/ProjectName.js
  src/components/ProjectName/ProjectName.stories.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.stories.js
  src/components/Selectbox/Selectbox.js
  src/components/Selectbox/Selectbox.stories.js
  src/components/index.js
Labels: ✨ Feature, 🔨 Refactor

#88 ChipInputSearch 컴포넌트 리팩토링, DND 컴포넌트 리팩토링
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ChipInputSearch/ChipInputSearch.stories.js
  src/components/DND/DND.js
  src/components/DND/DND.stories.js
Labels: 🔨 Refactor

#90 ProjectName 컴포넌트 리팩토링
  src/components/ProjectName/ProjectName.js
  src/components/ProjectName/ProjectName.stories.js
Labels: 🔨 Refactor

#91 Feat: LoginModalDialog 접근성, 반응형 추가
  src/components/Button/Button.js
  src/components/Dialog/Dialog.js
  src/components/Input/Input.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/containers/SignupModalDialog/SignupModalDialog.js
Labels: ✨ Feature

#92 TeamName 컴포넌트 생성, RadioButton과 ProjectName 컴포넌트 코드 일부 수정
  src/components/ProjectName/ProjectName.js
  src/components/ProjectName/ProjectName.stories.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.stories.js
  src/components/TeamName/TeamName.js
  src/components/TeamName/TeamName.stories.js
Labels: ✨ Feature

#95 PlanIntention 컴포넌트 생성 및 스토리북 작성, applyStyle 함수 적용
  src/components/Button/Button.js
  src/components/Input/Input.js
  src/components/PlanIntention/PlanIntention.js
  src/components/PlanIntention/PlanIntention.stories.js
  src/components/RadioButton/RadioButton.js
  src/components/Selectbox/Selectbox.js
  src/components/TeamName/TeamName.stories.js
  src/components/TextArea/TextArea.js
  src/components/TextArea/TextArea.stories.js
  src/components/index.js
Labels: ✨ Feature, 🔨 Refactor

#96 Feat: GithubLink Component 생성
  src/components/GithubLink/GithubLink.js
  src/components/GithubLink/GithubLink.stories.js
  src/components/Paragraph/Paragraph.stories.js
  src/components/index.js
Labels: ✨ Feature, 🌈 Style

#100 Input 컴포넌트의 propTypes 수정 및 TechStacks 컴포넌트 생성 및 스토리북 작성
  src/components/Input/Input.js
  src/components/TechStacks/TechStacks.js
  src/components/TechStacks/TechStacks.stories.js
  src/components/index.js
Labels: ✨ Feature

#102 ProjectThumbnail 컴포넌트 생성 및 스토리북 작성
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/components/ProjectThumbnail/ProjectThumbnail.stories.js
  src/components/TechStacks/TechStacks.js
  src/components/TechStacks/TechStacks.stories.js
  src/components/index.js
Labels: ✨ Feature

#106 PublicStatus 컴포넌트 생성 및 스토리북 작성, DeploymentStatus 컴포넌트 생성 및 스토리북 작성, ProjectDescription 컴포넌트 생성 및 스토리북 작성
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/DeploymentStatus/DeploymentStatus.stories.js
  src/components/ProjectDescription/ProjectDescription.js
  src/components/ProjectDescription/ProjectDescription.stories.js
  src/components/PublicStatus/PublicStatus.js
  src/components/PublicStatus/PublicStatus.stories.js
  src/components/index.js
Labels: ✨ Feature

#107 Refactor: Dialog, Heading, Modal, Paragraph, TextArea 컴포넌트 applyStyle 함수적용
  src/components/Dialog/Dialog.js
  src/components/Heading/Heading.js
  src/components/Modal/Modal.js
  src/components/Paragraph/Paragraph.js
  src/components/TextArea/TextArea.js
  src/components/TextArea/TextArea.stories.js
  src/containers/LoginModalDialog/LoginModalDialog.stories.js
Labels: 🔨 Refactor

#110 Feat: ProjectDuration Component 생성
  src/assets/Calendar.svg
  src/components/Container/Container.js
  src/components/Paragraph/Paragraph.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectDuration/ProjectDuration.stories.js
  src/components/SVGIcon/SVGIcon.js
  src/components/SVGIcon/SVGIcon.stories.js
  src/components/index.js
Labels: ✨ Feature

#113 Refactor: 콘솔창에 waring 현상 수정, 반응형 수정
  src/components/Button/Button.js
  src/components/Dialog/Dialog.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/GithubRepoInput/GithubRepoInput.stories.js
  src/components/Heading/Heading.js
  src/components/Input/Input.js
  src/components/Paragraph/Paragraph.js
  src/components/SVGIcon/SVGIcon.js
  src/components/index.js
  src/containers/LoginModalDialog/LoginModalDialog.js
Labels: 🔨 Refactor

#129 Feat: ProjectPage Component 반응형 추가
  src/assets/Express.svg
  src/assets/GithubBlue.svg
  src/assets/Javascript.svg
  src/assets/MySQL.svg
  src/assets/React.svg
  src/assets/Redux.svg
  src/assets/Sass.svg
  src/assets/StyledComponent.svg
  src/assets/Typescript.svg
  src/assets/WebSite.svg
  src/components/Heading/Heading.js
  src/components/SVGIcon/SVGIcon.js
  src/components/SkillIcon/SkillIcon.js
  src/components/SkillIcon/SkillIcon.stories.js
  src/components/index.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🌈 Style

#130 ProjectEditForm 컨테이너 생성 및 form에 들어갈 컴포넌트들 formik화 리팩토링 작업 완료
  src/components/A11yHidden/A11yHidden.js
  src/components/Button/Button.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ChipInputSearch/ChipInputSearch.stories.js
  src/components/DND/DND.js
  src/components/DND/DND.stories.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/DeploymentStatus/DeploymentStatus.stories.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/GithubRepoInput/GithubRepoInput.stories.js
  src/components/Image/Image.js
  src/components/Input/Input.js
  src/components/Input/Input.stories.js
  src/components/PlanIntention/PlanIntention.js
  src/components/PlanIntention/PlanIntention.stories.js
  src/components/ProjectDescription/ProjectDescription.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectDuration/ProjectDuration.stories.js
  src/components/ProjectName/ProjectName.js
  src/components/ProjectName/ProjectName.stories.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/components/ProjectThumbnail/ProjectThumbnail.stories.js
  src/components/PublicStatus/PublicStatus.js
  src/components/PublicStatus/PublicStatus.stories.js
  src/components/RadioButton/RadioButton.js
  src/components/RadioButton/RadioButton.stories.js
  src/components/TeamName/TeamName.js
  src/components/TeamName/TeamName.stories.js
  src/components/TechStacks/TechStacks.js
  src/components/TechStacks/TechStacks.stories.js
  src/components/TextArea/TextArea.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/containers/ProjectEditForm/ProjectEditForm.stories.js
  src/containers/index.js
  src/pages/ProjectEdit/ProjectEditPage.js
Labels: ✨ Feature, 🔨 Refactor

#134 프로젝트 등록 페이지에서 작성한 내용을 데이터베이스에 저장할 수 있도록 구현
  src/apis/ajax.js
  src/apis/image.js
  src/apis/project.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/ChipInputSearch/ChipInputSearch.stories.js
  src/components/DND/DND.js
  src/components/DND/DND.stories.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/DeploymentStatus/DeploymentStatus.stories.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/GithubRepoInput/GithubRepoInput.stories.js
  src/components/PlanIntention/PlanIntention.stories.js
  src/components/ProjectDescription/ProjectDescription.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectDuration/ProjectDuration.stories.js
  src/components/ProjectName/ProjectName.js
  src/components/ProjectName/ProjectName.stories.js
  src/components/ProjectThumbnail/ProjectThumbnail.stories.js
  src/components/PublicStatus/PublicStatus.js
  src/components/PublicStatus/PublicStatus.stories.js
  src/components/TeamName/TeamName.js
  src/components/TeamName/TeamName.stories.js
  src/components/TechStacks/TechStacks.stories.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/pages/ProjectEdit/ProjectEditPage.js
Labels: ✨ Feature, 🔨 Refactor

#136 Feat: ProjectPage Component 반응형 추가
  src/assets/HeartRed.svg
  src/components/SkillIcon/SkillIcon.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature

#137 : HeartRed svg 에서 stroke 수정
  src/assets/HeartRed.svg
Labels: 🐞 BugFix

#146 ProjectPage Component 좋아요 버튼 애니메이션 추가
  src/components/Container/Container.js
  src/components/SkillIcon/SkillIcon.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🌈 Style

#147 프로젝트 등록 페이지 피그마 시안과 맞게 스타일링하고 반응형 스타일링도 구현
  src/components/Button/Button.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/Input/Input.js
  src/components/PlanIntention/PlanIntention.js
  src/components/ProjectDescription/ProjectDescription.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectName/ProjectName.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/components/PublicStatus/PublicStatus.js
  src/components/TeamName/TeamName.js
  src/components/TechStacks/TechStacks.js
  src/components/TextArea/TextArea.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/pages/ProjectEdit/ProjectEditPage.js
Labels: ✨ Feature, 🔨 Refactor

#150 프로젝트 등록페이지에 form validation 적용
  src/components/DND/DND.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/PlanIntention/PlanIntention.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectName/ProjectName.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/utils/index.js
  src/utils/validationSchema.js
Labels: ✨ Feature

#156 Feat: ProjectPage 좋아요 버튼 기능 구현
  src/app/App.js
  src/components/ProjectExplanation/ProjectExplanation.js
  src/components/index.js
  src/pages/Project/ProjectPage.js
  src/utils/parseHtmlAndHighlighter.js
Labels: ✨ Feature, 🔨 Refactor

#159 Refactor: Project Component 이름수정
  src/pages/Project/ProjectPage.js
Labels: 🔨 Refactor

#160 TextArea 크기 조정 안되게끔 수정 및 github_url, deploy_url 요소들의 placeholder 문구 수정, input 요소들의 autocomplete 비활성화, Radio컴포넌트들 default 옵션 지정해주기
  package-lock.json
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/Input/Input.js
  src/components/TextArea/TextArea.js
  src/containers/ProjectEditForm/ProjectEditForm.js
Labels: 🔨 Refactor

#163 Refactor: Projectpage, Skillicon 수정
  src/assets/AWSEC2.svg
  src/assets/AWSElasticBeanstalk.svg
  src/assets/AWSRDS.svg
  src/assets/AWSS3.svg
  src/assets/Apache.svg
  src/assets/C.svg
  src/assets/CPP.svg
  src/assets/CSHARP.svg
  src/assets/Css3.svg
  src/assets/Dart.svg
  src/assets/Django.svg
  src/assets/Electron.svg
  src/assets/Firebase.svg
  src/assets/Flutter.svg
  src/assets/GraphQL.svg
  src/assets/Html5.svg
  src/assets/Java.svg
  src/assets/Javascript.svg
  src/assets/Jest.svg
  src/assets/Mobx.svg
  src/assets/MongoDB.svg
  src/assets/NextJS.svg
  src/assets/NodeJS.svg
  src/assets/Prisma.svg
  src/assets/Python.svg
  src/assets/React.svg
  src/assets/Ruby.svg
  src/assets/Scala.svg
  src/assets/Spring.svg
  src/assets/Typescript.svg
  src/assets/Vue.svg
  src/components/SkillIcon/SkillIcon.js
  src/components/SkillIcon/SkillIcon.stories.js
  src/pages/Project/ProjectPage.js
Labels: 🐞 BugFix, 🔨 Refactor

#173 ChipInputSearch Input 아무곳이나 눌러도 focus 가능하게끔 수정 및 ChipInputSearch에서 검색할 기술스택 목록들 데이터베이스에서 불러오기, Radio 컴포넌트들에 tab control이 가능하게 변경, 키보드로 컨트롤할때 tab이 되는 요소들에 outline처리, Form 요소의 validation 스타일링과 필수 항목들 먼저 보여주기 구현
  src/apis/ajax.js
  src/apis/techStacks.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/DeploymentStatus/DeploymentStatus.js
  src/components/FormErrorMessage/FormErrorMessage.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/Input/Input.js
  src/components/PlanIntention/PlanIntention.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectName/ProjectName.js
  src/components/RadioButton/RadioButton.js
  src/components/TextArea/TextArea.js
  src/components/index.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/utils/validationSchema.js
Labels: 🔨 Refactor

#182 GithubRepo validation이 완벽히 거르지 못한 이슈 해결
  src/components/GithubRepoInput/GithubRepoInput.js
  src/utils/validationSchema.js
Labels: 🐞 BugFix

#178 Feat: ProjectPage 수정 및 Nav 생성, ProjectDuration 수정
  src/assets/GithubBlueDisable.svg
  src/assets/WebSiteDisable.svg
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectNav/ProjectNav.js
  src/components/SVGIcon/SVGIcon.js
  src/components/SVGIcon/SVGIcon.stories.js
  src/components/index.js
  src/containers/LoginModalDialog/LoginModalDialog.stories.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🔨 Refactor

#184 BugFix: 프로젝트 등록페이지에서 적용된 블러킹이 다른페이지로 이동해도 유효한 버그를 해결, form의 input안에 들어오는 글자에 패딩주기, DND 컴포넌트에 여백이 있는 이미지 넣으면 뒷배경 파랗게 보이는 현상 해결
  src/components/DND/DND.js
  src/components/Input/Input.js
  src/components/TextArea/TextArea.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/pages/ProjectEdit/ProjectEditPage.js
Labels: 🐞 BugFix, 🔨 Refactor

#186 ProjectPage 모바일뷰에서 기술스택 정렬 수정, SkillIcon 추가, Paragraph 글이 길어지면 레이아웃 벗어나는 사항 수정
  src/assets/Angular.svg
  src/assets/Aws.svg
  src/assets/Bootstrap.svg
  src/assets/CouchDB.svg
  src/assets/DynamoDB.svg
  src/assets/Git.svg
  src/assets/Github.svg
  src/assets/JQuery.svg
  src/assets/Jekyll.svg
  src/assets/Linux.svg
  src/assets/MariaDB.svg
  src/assets/MaterialUI.svg
  src/assets/Oracle.svg
  src/assets/PostCSS.svg
  src/assets/Redis.svg
  src/assets/RethinkDB.svg
  src/assets/Rollup.svg
  src/assets/RxJS.svg
  src/assets/Svelte.svg
  src/assets/TailwindCSS.svg
  src/assets/Tomcat.svg
  src/assets/Webpack.svg
  src/components/Button/Button.js
  src/components/Paragraph/Paragraph.js
  src/components/SkillIcon/SkillIcon.js
  src/components/SkillIcon/SkillIcon.stories.js
  src/pages/Project/ProjectPage.js
Labels: 🔨 Refactor

#190 포트폴리오 수정 페이지 전반적인 레이아웃 작업, 포트폴리오 수정 페이지 스타일링, 이미지 제거 버튼과 회원 탈퇴 버튼 생성
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/Paragraph/Paragraph.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
Labels: ✨ Feature

#202 포트폴리오 수정 페이지 containers들로 분리
  src/containers/PortfolioEditContents/PortfolioEditContents.js
  src/containers/PortfolioEditProfile/PortfolioEditProfile.js
  src/containers/index.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
Labels: 🔨 Refactor

#204 포트폴리오 수정페이지에 들어갔을때 실제 데이터를 받아와 띄워주는 작업, 포트폴리오 수정 페이지에 이미지 제거버튼 기능 구현, 포트폴리오 수정페이지에서 저장버튼 눌렀을때 유저정보 수정되게 구현
  src/apis/ajax.js
  src/apis/portfolio.js
  src/components/Button/Button.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/TechStacks/TechStacks.js
  src/containers/PortfolioEditContents/PortfolioEditContents.js
  src/containers/PortfolioEditProfile/PortfolioEditProfile.js
  src/pages/Portfolio/PortfolioPage.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
  src/store/modules/auth/authActionCreator.js
  src/store/modules/auth/authMiddleware.js
Labels: ✨ Feature

#195 Refactor: api 함수 파일분리, ProjectPage 스피너 생성
  src/apis/ajax.js
  src/apis/project.js
  src/assets/Docker.svg
  src/assets/Firestore.svg
  src/assets/Suits.svg
  src/assets/Vue.svg
  src/components/Heading/Heading.js
  src/components/ProjectExplanation/ProjectExplanation.js
  src/components/ProjectNav/ProjectNav.js
  src/components/SVGIcon/SVGIcon.js
  src/components/SVGIcon/SVGIcon.stories.js
  src/components/SkillIcon/SkillIcon.js
  src/components/SkillIcon/SkillIcon.stories.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/pages/Project/ProjectPage.js
  src/utils/parseHtmlAndHighlighter.js
Labels: ✨ Feature, 🔨 Refactor

#214 포트폴리오 수정 페이지의 input창의 placeholder와 입력 텍스트 폰트 크기 수정, 포트폴리오 수정페이지의 validation 작업
  src/components/DND/DND.js
  src/components/FormErrorMessage/FormErrorMessage.js
  src/components/GithubRepoInput/GithubRepoInput.js
  src/components/Input/Input.js
  src/components/PlanIntention/PlanIntention.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectName/ProjectName.js
  src/containers/PortfolioEditContents/PortfolioEditContents.js
  src/containers/PortfolioEditProfile/PortfolioEditProfile.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
  src/utils/index.js
  src/utils/portfolioValidationSchema.js
  src/utils/projectValidationSchema.js
Labels: ✨ Feature, 🔨 Refactor

#218 ProjectPage, LoginModalDialog, ProjectExplanation 수정
  src/components/ProjectExplanation/ProjectExplanation.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#220 BugFix: 스켈레톤UI 수정
  src/pages/Project/ProjectPage.js
Labels: 🐞 BugFix

#221 회원 탈퇴 버튼 위치 재배치 및 기능 구현
  src/apis/ajax.js
  src/apis/auth.js
  src/components/Button/Button.js
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/Dialog/Dialog.js
  src/components/Input/Input.js
  src/components/Modal/Modal.js
  src/containers/PortfolioEditProfile/PortfolioEditProfile.js
  src/containers/WithdrawalModalDialog/WithdrawalModalDialog.js
  src/containers/index.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
  src/store/modules/auth/authMiddleware.js
Labels: ✨ Feature

#225 Refactor: SKillIcon 이미지 추가, ModalDialog 수정
  src/assets/Emotion.svg
  src/assets/Hugo.svg
  src/assets/Jsp.svg
  src/assets/Koa.svg
  src/assets/Less.svg
  src/assets/MsSQL.svg
  src/assets/NGRX.svg
  src/assets/NginX.svg
  src/assets/NuxtJS.svg
  src/assets/PHP.svg
  src/assets/Parcel.svg
  src/assets/PostgreSQL.svg
  src/assets/ReactHooks.svg
  src/assets/ReactStrap.svg
  src/assets/Reactnative.svg
  src/assets/VueX.svg
  src/components/Dialog/Dialog.js
  src/components/SkillIcon/SkillIcon.js
  src/components/SkillIcon/SkillIcon.stories.js
  src/containers/HeaderBar/HeaderBar.js
  src/containers/LoginModalDialog/LoginModalDialog.js
  src/containers/LoginModalDialog2/LoginModalDialog2.js
  src/containers/ModalDialog/ModalDialog.js
  src/containers/index.js
  src/pages/Project/ProjectPage.js
Labels: ✨ Feature, 🔨 Refactor

#222 포트폴리오 페이지의 백그라운드를 변경하는 기능 구현, 프로젝트 수정페이지 구현, 회원탈퇴 모달 ModalDialog컴포넌트 사용하여 리팩토링
  src/apis/ajax.js
  src/apis/project.js
  src/assets/Palette.svg
  src/components/ChipInputSearch/ChipInputSearch.js
  src/components/DND/DND.js
  src/components/ProjectDuration/ProjectDuration.js
  src/components/ProjectThumbnail/ProjectThumbnail.js
  src/components/SVGIcon/SVGIcon.js
  src/components/TechStacks/TechStacks.js
  src/containers/ModalDialog/ModalDialog.js
  src/containers/PortfolioEditProfile/PortfolioEditProfile.js
  src/containers/PortfolioProfile/PortfolioProfile.js
  src/containers/ProjectEditForm/ProjectEditForm.js
  src/containers/WithdrawalModalDialog/WithdrawalModalDialog.js
  src/pages/Portfolio/PortfolioPage.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
  src/pages/ProjectEdit/ProjectEditPage.js
Labels: ✨ Feature

#228 Refactor: ProjectPage 컴포넌트 분리 및 수정
  src/components/Dialog/Dialog.js
  src/components/DivisionLine/DivisionLine.js
  src/components/SkillIcon/SkillIcon.js
  src/components/index.js
  src/pages/Project/ProjectPage.js
  src/utils/dateFormMaker.js
  src/utils/index.js
Labels: ✨ Feature, 🔨 Refactor

#230 Bugfix: ProjectPage 로딩에러나는 문제 해결
  src/pages/Project/ProjectPage.js
Labels: 🐞 BugFix

#231 포트폴리오 수정 페이지에서 깃헙 로그인시 이메일 validation오류 나는 버그
  src/pages/PortfolioEdit/PortfolioEditPage.js
Labels: 🐞 BugFix

#232 포트폴리오 수정 페이지에서 레이아웃 오류
  src/components/ProjectDuration/ProjectDuration.js
Labels: 🐞 BugFix

#234 Refactor: SkillIcon 이미지 수정, PortfolioEditPage console.log 삭제
  src/assets/NodeJS.svg
  src/assets/React.svg
  src/assets/Reactnative.svg
  src/assets/VueX.svg
  src/components/SkillIcon/SkillIcon.js
  src/pages/PortfolioEdit/PortfolioEditPage.js
Labels: 🔨 Refactor

#239 Refactor: ProjectPage 프로젝트 설명 a태그 스타일링 수정
  src/components/ProjectExplanation/ProjectExplanation.js
Labels: 🔨 Refactor

#241 Refactor: SKillIcon python아이콘 수정
  src/assets/Python.svg
Labels: 🔨 Refactor
